export { default as CarImage } from './araba.jpeg';
export { default as PhoneImage } from './phone.jpeg';
export { default as PostImage } from './post.png';
export { default as TrendyolPaperImage } from './trendyol_cek.png';
export { default as TVImage } from './tv.jpeg';
export { default as ProductImage } from './product-image.png';
export { default as UserLogoImage } from './user-logo.png';
export { default as UserImage } from './user.png';
export { default as CheckImage } from './check-image.png';